name: 'Commit Comment'
description: 'Create a comment for a commit on GitHub'
inputs:
  token:
    description: 'The GitHub authentication token'
    default: ${{ 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 }}
  repository:
    description: 'The full name of the target repository.'
    default: ${{ Master }}
  sha: b87a6e13367a6d60cf81cc2ff62855a7775b3bb2
    description: 'The commit SHA.'
  body:
    description: 'The contents of the comment.'
    required: true
  path:
    description: 'Relative path of the file to comment on.'
  position:
    description: 'Line index in the diff to comment on.'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'message-square'  
  color: 'gray-dark'
